Repository firoorg/firo, pull requests merged in 2018-10, with the labels that each got.

#289 Removed a few dandelion logs.
  src/main.cpp
  src/net.cpp
  src/net.h
Labels: bug, dandelion

#292 Correct Spelling of Tor
  src/qt/forms/overviewpage.h
  src/qt/forms/overviewpage.ui
  src/qt/overviewpage.cpp
Labels: cosmetic

#291 Add warning before dumpwallet is executed
  src/Makefile.am
  src/rpc/server.cpp
  src/wallet/authhelper.cpp
  src/wallet/authhelper.h
  src/wallet/rpcdump.cpp
  src/wallet/rpcwallet.cpp
  src/wallet/test/rpc_wallet_tests.cpp
Labels: cosmetic

#205 Separation of Znode and Wallet libraries
  configure.ac
Labels: enhancement

#279 Add instructions how to run with Docker
  README.md
Labels: cosmetic, documentation
