Repository firoorg/firo, pull requests merged in 2019-07, with the labels that each got.

#480 Remint in insight
  src/qt/zc2sigmapage.cpp
  src/script/script.cpp
  src/script/standard.cpp
  src/txdb.cpp
Labels: GUI, Sigma

#479 Handle disconnectTip for sigma.
  src/hdmint/tracker.cpp
  src/hdmint/tracker.h
  src/main.cpp
  src/qt/walletmodel.cpp
Labels: GUI, Sigma

#487 Disable Exodus from building by default
  Jenkinsfile
  configure.ac
  src/Makefile.am
  src/Makefile.exodus.include
  src/Makefile.exodustest.include
  src/Makefile.qt.include
  src/Makefile.test.include
  src/httprpc.cpp
  src/init.cpp
  src/main.cpp
  src/mbstring.cpp
  src/mbstring.h
  src/qt/bitcoingui.cpp
  src/qt/bitcoingui.h
  src/qt/walletframe.cpp
  src/qt/walletframe.h
  src/qt/walletview.cpp
  src/qt/walletview.h
  src/rpc/register.h
  src/test/mbstring_tests.cpp
  src/test/test_bitcoin.cpp
Labels: Exodus

#488 Support build exodus transaction using sigma.
  src/Makefile.exodustest.include
  src/exodus/exodus.cpp
  src/exodus/exodus.h
  src/exodus/test/build_tx_tests.cpp
  src/exodus/wallettxs.cpp
  src/exodus/wallettxs.h
  src/test/fixtures.cpp
  src/test/fixtures.h
Labels: Exodus

#497 Disable sigma on legacy wallet
  qa/pull-tester/rpc-tests.py
  qa/rpc-tests/disable_nonhdsigma.py
  qa/rpc-tests/enable_hdsigma.py
  src/Makefile.qt.include
  src/hdmint/tracker.cpp
  src/init.cpp
  src/qt/bitcoingui.cpp
  src/qt/bitcoingui.h
  src/qt/forms/blanksigmadialog.ui
  src/qt/sigmadialog.cpp
  src/qt/sigmadialog.h
  src/qt/walletmodel.cpp
  src/qt/walletview.cpp
  src/qt/walletview.h
  src/wallet/crypter.cpp
  src/wallet/rpcwallet.cpp
  src/wallet/sigmaspendbuilder.cpp
  src/wallet/txbuilder.cpp
  src/wallet/wallet.cpp
  src/wallet/wallet.h
Labels: Sigma

#498 Fix transaction list when mint with rpc
  src/wallet/wallet.cpp
Labels: Sigma

#496 List from mempool fix
  src/hdmint/tracker.cpp
  src/hdmint/tracker.h
  src/init.cpp
  src/main.cpp
  src/wallet/wallet.cpp
Labels: Sigma

#507 Compilation flags extension
  src/wallet/rpcdump.cpp
Labels: enhancement

#516 Patching Sigma Generator creation
  src/main.cpp
  src/secp256k1/include/GroupElement.h
  src/secp256k1/src/cpp/GroupElement.cpp
  src/sigma/params.cpp
  src/sigma/test/coin_spend_tests.cpp
  src/sigma/test/coin_tests.cpp
  src/sigma/test/protocol_tests.cpp
  src/sigma/test/serialize_test.cpp
  src/zerocoin_v3.cpp
  src/zerocoin_v3.h
Labels: Sigma

#515 Sigma Cleanup
  src/hdmint/tracker.cpp
  src/hdmint/tracker.h
  src/hdmint/wallet.cpp
  src/wallet/wallet.cpp
Labels: cosmetic

#505 Fix Sigma list issues during "pending" mint/spend (ie. mempool)
  qa/pull-tester/rpc-tests.py
  qa/rpc-tests/hdmint_mempool_zap.py
  qa/rpc-tests/sigma_zapwalletmints.py
  qa/rpc-tests/sigma_zapwalletmints_unconf_trans.py
  src/hdmint/tracker.cpp
  src/hdmint/tracker.h
  src/init.cpp
  src/main.cpp
  src/txmempool.cpp
Labels: bug, cosmetic

#508 Dump/Import wallet RPC Updates
  src/hdmint/wallet.cpp
  src/hdmint/wallet.h
  src/wallet/rpcdump.cpp
  src/wallet/wallet.cpp
  src/wallet/walletdb.h
Labels: bug, enhancement

#510 Implement sigma primitives for Exodus
  src/Makefile.exodus.include
  src/Makefile.exodustest.include
  src/exodus/sigma.cpp
  src/exodus/sigma.h
  src/exodus/test/sigma_tests.cpp
  src/secp256k1/src/cpp/Scalar.cpp
Labels: Exodus

#506 Support exodus payload parsing for sigma spend transaction
  src/Makefile.exodustest.include
  src/exodus/exodus.cpp
  src/exodus/exodus.h
  src/exodus/test/exodus_handler_tx.cpp
Labels: Exodus

#529 Add flag to control sigma feature for token
  src/exodus/createpayload.cpp
  src/exodus/createpayload.h
  src/exodus/rpcrequirements.cpp
  src/exodus/rpcrequirements.h
  src/exodus/rpctx.cpp
  src/exodus/rules.cpp
  src/exodus/sp.cpp
  src/exodus/sp.h
  src/exodus/tx.cpp
  src/exodus/tx.h
  src/rpc/client.cpp
Labels: Exodus

#530 Fix memory
  src/hdmint/wallet.cpp
  src/txmempool.cpp
  src/zerocoin_v3.cpp
Labels: bug

#536 Fix issue with parsing legacy HD keypath
  src/wallet/rpcdump.cpp
  src/wallet/wallet.cpp
  src/wallet/walletdb.h
Labels: bug, high priority

#549 Rename zerocoin_v3.h and zerocoin_v3.cpp to sigma.[h|cpp]
  src/Makefile.am
  src/hdmint/hdmint.h
  src/hdmint/mintpool.cpp
  src/hdmint/tracker.cpp
  src/hdmint/wallet.cpp
  src/main.cpp
  src/miner.cpp
  src/primitives/block.h
  src/qt/sigmadialog.cpp
  src/qt/walletmodel.cpp
  src/rpc/rawtransaction.cpp
  src/sigma.cpp
  src/sigma.h
  src/test/fixtures.cpp
  src/test/sigma_manymintspend_test.cpp
  src/test/sigma_mintspend_numinputs.cpp
  src/test/sigma_mintspend_test.cpp
  src/test/sigma_partialspend_mempool_tests.cpp
  src/test/sigma_state_tests.cpp
  src/test/sigma_transition_test.cpp
  src/test/test_bitcoin.cpp
  src/test/zerocoin_tests2_v3.cpp
  src/test/zerocoin_tests3_v3.cpp
  src/wallet/rpcwallet.cpp
  src/wallet/sigmaspendbuilder.cpp
  src/wallet/test/sigma_tests.cpp
  src/wallet/wallet.cpp
  src/zerocoin.cpp
Labels: cosmetic

#551 Remint tests for same serial in one block and forged sigma mint desti…
  src/test/remint_tests.cpp
Labels: Tests

#560 Fixed potential deadlock in znode code
  src/znodeman.h
Labels: bug

#557 Fix Subtract fee from amount
  src/wallet/wallet.cpp
Labels: bug

#558 Fix incorrect treating of height for sigma verification
  src/sigma.cpp
Labels: bug
