Repository firoorg/firo, pull requests merged in 2019-12, with the labels that each got.

#641 Implement BIP39 (Mnemonic code for generating deterministic keys)
  qa/rpc-tests/keypool.py
  qa/rpc-tests/test_framework/util.py
  qa/rpc-tests/wallet-dump.py
  src/Makefile.am
  src/Makefile.qt.include
  src/Makefile.test.include
  src/hdmint/wallet.cpp
  src/init.cpp
  src/qt/bitcoin.cpp
  src/qt/forms/notifymnemonic.ui
  src/qt/forms/recover.ui
  src/qt/notifymnemonic.cpp
  src/qt/notifymnemonic.h
  src/qt/recover.cpp
  src/qt/recover.h
  src/support/allocators/secure.h
  src/wallet/bip39.cpp
  src/wallet/bip39.h
  src/wallet/bip39_english.h
  src/wallet/crypter.cpp
  src/wallet/crypter.h
  src/wallet/mnemoniccontainer.cpp
  src/wallet/mnemoniccontainer.h
  src/wallet/rpcdump.cpp
  src/wallet/rpcwallet.cpp
  src/wallet/test/mnemonic_tests.cpp
  src/wallet/wallet.cpp
  src/wallet/wallet.h
  src/wallet/walletdb.cpp
  src/wallet/walletdb.h
Labels: enhancement, high priority

#787 Fix issue with old Zerocoin import
  src/wallet/rpcdump.cpp
Labels: bug

#788 Fix issue with upgrade of encrypted legacy wallets to Sigma
  src/wallet/crypter.cpp
Labels: bug

#786 Fixed tor library picking wrong openssl library on MacOS
  configure.ac
Labels: bug

#796 Qt Sigma page updates
  src/qt/sigmacoincontroldialog.cpp
  src/qt/sigmadialog.cpp
  src/qt/sigmadialog.h
  src/qt/walletmodel.cpp
  src/qt/walletmodel.h
Labels: bug, cosmetic

#791 Showing Sigma balance at overview page
  src/qt/forms/overviewpage.ui
  src/qt/overviewpage.cpp
  src/qt/overviewpage.h
Labels: cosmetic

#792 Upstream Depends updates
  configure.ac
  contrib/gitian-descriptors/gitian-osx.yml
  depends/Makefile
  depends/config.site.in
  depends/funcs.mk
  depends/hosts/darwin.mk
  depends/packages/bdb.mk
  depends/packages/expat.mk
  depends/packages/fontconfig.mk
  depends/packages/libX11.mk
  depends/packages/libXau.mk
  depends/packages/libXext.mk
  depends/packages/libxcb.mk
  depends/packages/miniupnpc.mk
  depends/packages/native_biplist.mk
  depends/packages/native_cctools.mk
  depends/packages/native_cdrkit.mk
  depends/packages/native_ds_store.mk
  depends/packages/native_mac_alias.mk
  depends/packages/native_protobuf.mk
  depends/packages/qt.mk
  depends/packages/xcb_proto.mk
  depends/packages/xextproto.mk
  depends/packages/xproto.mk
  depends/packages/xtrans.mk
  depends/packages/zlib.mk
  src/Makefile.am
Labels: build-system

#801 Ui freezing fix
  src/qt/overviewpage.cpp
Labels: bug

#799 Exclude locked coins from Available to mint amount
  src/qt/sigmadialog.cpp
  src/qt/sigmadialog.h
  src/qt/walletmodel.cpp
  src/qt/walletmodel.h
  src/wallet/wallet.cpp
  src/wallet/wallet.h
Labels: bug, cosmetic

#804 Updating total balance when spending
  src/qt/overviewpage.cpp
Labels: bug

#773 Fix Exodus mint creation
  qa/pull-tester/rpc-tests.py
  qa/rpc-tests/exodus_sendmint_wallet_encryption.py
  src/exodus/rpctx.cpp
  src/exodus/sigmawallet.cpp
Labels: bug, exodus

#807 Fixing transaction sync when recovering
  src/chainparams.cpp
  src/consensus/params.h
  src/wallet/wallet.cpp
  src/wallet/wallet.h
Labels: bug

#809 SetHDChain fix
  src/wallet/wallet.cpp
  src/wallet/wallet.h
  src/wallet/walletdb.cpp
Labels: bug
