Repository firoorg/firo, pull requests merged in 2021-09, with the labels that each got.

#1068 Fixing the usage of comma or dot as a separator
  src/qt/bitcoinamountfield.cpp
  src/qt/forms/lelantusdialog.ui
  src/qt/lelantusdialog.cpp
Labels: cosmetic

#1069 GUI freeze fix during batch verification
  src/batchproof_container.cpp
  src/batchproof_container.h
  src/validation.cpp
Labels: bug, GUI

#1072 Devnet chain
  contrib/seeds/generate-seeds.py
  contrib/seeds/nodes_dev.txt
  src/chainparams.cpp
  src/chainparamsbase.cpp
  src/chainparamsbase.h
  src/chainparamsseeds.h
  src/consensus/params.h
  src/miner.cpp
  src/pow.cpp
  src/qt/networkstyle.cpp
  src/wallet/wallet.cpp
Labels: testnet

#1062 Is lelantus
  qa/pull-tester/rpc-tests.py
  qa/rpc-tests/llmq-is-cl-conflicts.py
  qa/rpc-tests/llmq-is-lelantus.py
  src/chainparams.cpp
  src/consensus/params.h
  src/dsnotificationinterface.cpp
  src/evo/spork.h
  src/init.cpp
  src/llmq/quorums_chainlocks.cpp
  src/llmq/quorums_chainlocks.h
  src/llmq/quorums_init.cpp
  src/llmq/quorums_instantsend.cpp
  src/llmq/quorums_instantsend.h
  src/miner.cpp
  src/net_processing.cpp
  src/qt/forms/createpcodedialog.ui
  src/qt/forms/sendtopcodedialog.ui
  src/qt/guiconstants.h
  src/qt/transactiondesc.cpp
  src/qt/transactionfilterproxy.cpp
  src/qt/transactionfilterproxy.h
  src/qt/transactionrecord.cpp
  src/qt/transactionrecord.h
  src/qt/transactiontablemodel.cpp
  src/qt/transactiontablemodel.h
  src/qt/transactionview.cpp
  src/qt/transactionview.h
  src/qt/walletmodel.cpp
  src/qt/walletmodel.h
  src/rpc/blockchain.cpp
  src/rpc/client.cpp
  src/rpc/rawtransaction.cpp
  src/sync.h
  src/txmempool.cpp
  src/validation.cpp
  src/validationinterface.cpp
  src/wallet/rpcwallet.cpp
  src/wallet/wallet.cpp
  src/wallet/wallet.h
Labels: Lelantus

#1067 lelantus .. is not allowed for legacy wallet error fixed
  src/wallet/rpcwallet.cpp
Labels: Lelantus
